apiVersion: v1
kind: Service

metadata:
  name: go-rest-api-service
  labels:
    app: go-rest-api   # IMPORTANT

spec:
  selector:
    app: go-rest-api

  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080

  type: ClusterIP