apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ .Release.Name }}

  labels:
    release: prometheus

spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}

  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  endpoints:
    - port: http
      path: /metrics
      interval: 15s